$(function(){
	//--顶部语言选择
	$('.topBtn').find('.li_01').hover(
	   function(){
		   $(this).find('dl').show();
		   },
	   function(){
		   $(this).find('dl').hide();
		   }
	)
	//--首页焦点图
	//--
	$('.indexPart2').find('li:last').css('background','none');
	$('.sideNav').find('li:last').css('background','none');
	$('.memberNav').find('ul').find('a:last').css('border','0px');
	$('.member_01').find('li:last').css('background','none');
	$('.member_02').find('tr:last').find('td').css('background','none');
	$('.Performance2').find('tr').eq(1).find('td').css('background','none');
	//--首页会员风采
	$('.listHover').find('li').hover(
	   function(){
		   $(this).addClass('liNow');
		   },
	   function(){
		   $(this).removeClass('liNow');
		   }
	)
	//--选项卡
	$('.tabContentDiv').find('.tabContent:first').show();
	$('.tab').each(function(i){
		$(this).find('li').each(function(ii){
			$(this).hover(
			function(){
				$('.tab').eq(i).find('li').removeClass('liNow');
				$(this).addClass('liNow');
				$('.tabContentDiv').eq(i).find('.tabContent').hide();
				$('.tabContentDiv').eq(i).find('.tabContent').eq(ii).show();
				},
			function(){}	
				)
			})
		})
	//--发行公告
	//--会员左侧菜单
	$('.memberNav').find('h2').each(function(i){
		$(this).click(function(){
			if($(this).hasClass('h2Now')){
				$('.memberNav').find('h2').removeClass('h2Now');
				$('.memberNav').find('.list').hide();
				}else{
					$('.memberNav').find('h2').removeClass('h2Now');
					$('.memberNav').find('.list').hide();
					$(this).addClass('h2Now');
					$('.memberNav').find('.list').eq(i).show();
					}
			})
		})
	//--历史业绩查询弹出层
	$('.Performance2').find('td').find('a').click(function(){
		$('.Performance2Layer').fadeIn(200);
		})
	$('.Performance2Layer').hover(
	   function(){},
	   function(){
		   $(this).hide();
		   }
	)
	//--文本输入框文字消失显示
	//--下拉选择框
	//--广告
	$('.sideLad').find('.close').click(function(){
		$('.sideLad').fadeOut(200);
		})
	$('.sideRad').find('.close').click(function(){
		$('.sideRad').fadeOut(200);
		})
	//--首页资讯动态
	$('.indexPart6').find('.name2:last').css('background','none');
	$('.indexPart6').find('li').hover(
	   function(){
		   $('.indexPart6').find('li').removeClass('liNow');
		   $(this).addClass('liNow');
		   },
	   function(){}
	)
	//--新增js---2016-03-23
	//--首页会员风采
	//--首页会员产品
	//--首页认购意向
	$('.indexPart11').find('.bd').each(function(){
		$(this).slide({mainCell:"ul",autoPlay:true,effect:"topMarquee",vis:5,interTime:50,trigger:"click"});
		})
	//--04-会员风采-04产品详情-2
	//--08-会员中心-05业绩提交-04弹出层
	//--我要出售
	$('.yqtjSellLayer').find('table').find('tr:last').find('td').css('border','0px');
	$('.yqtjSellLayer').find('.close').click(function(){
		$('.yqtjSellLayer').fadeOut(200);
		})
	$('.yqtjSellLayerA').click(function(){
		$('.yqtjSellLayer').fadeIn(200);
		})
	$('.yqtjSellLayer').find('.btn').find('a').each(function(i){
		$(this).click(function(){
			$('.yqtjSellLayer').find('.btn').find('a').removeClass('a1');
			$(this).addClass('a1');
			$('.yqtjSellLayer').find('table').hide();
			$('.yqtjSellLayer').find('table').eq(i).fadeIn(200);
			})
		})
	$('.yqtjList').find('tr:last').find('td').css('border','0px');
	//--
	$('.yqtjLayerA').click(function(){
		$('.yqtjLayer').fadeIn(200);
		})
	$('.yqtjLayer').find('.close').click(function(){
		$('.yqtjLayer').fadeOut(200);
		})
	$('.yqtjLayer').find('th:first').css('border-left','0px');
	$('.yqtjLayer').find('tr').find('td:first').css('border-left','0px');
	$('.yqtjLayer').find('tr').eq(1).find('td').css('border-top','0px');
	//
	})