<?php
 return array (
  0 => 
  array (
    'component' => 'grid',
    'livname' => '微请柬列表',
    'proname' => 'wqj_list',
    'cfg_add_key' => '1',
    'cfg_edit_key' => '1',
    'cfg_del_key' => '1',
    'cfg_page_key' => '1',
    'cfg_handsort_key' => '1',
    'cfg_brower_key' => '0',
    'cfg_top_key' => '0',
    'cfg_pub_key' => '0',
    'fieldtable' => 0,
  ),
  1 => 
  array (
    'component' => 'grid',
    'livname' => '报名',
    'proname' => 'registration',
    'cfg_add_key' => '1',
    'cfg_edit_key' => '1',
    'cfg_del_key' => '1',
    'cfg_page_key' => '1',
    'cfg_handsort_key' => '0',
    'cfg_brower_key' => '0',
    'cfg_top_key' => '0',
    'cfg_pub_key' => '0',
    'fieldtable' => 1,
  ),
  2 => 
  array (
    'component' => 'grid',
    'livname' => '图片展示',
    'proname' => 'images',
    'cfg_add_key' => '1',
    'cfg_edit_key' => '1',
    'cfg_del_key' => '1',
    'cfg_page_key' => '1',
    'cfg_handsort_key' => '1',
    'cfg_brower_key' => '0',
    'cfg_top_key' => '0',
    'cfg_pub_key' => '0',
    'fieldtable' => 2,
  ),
  3 => 
  array (
    'component' => 'grid',
    'livname' => '赞助商',
    'proname' => 'sponsor',
    'cfg_add_key' => '1',
    'cfg_edit_key' => '1',
    'cfg_del_key' => '1',
    'cfg_page_key' => '1',
    'cfg_handsort_key' => '1',
    'cfg_brower_key' => '0',
    'cfg_top_key' => '0',
    'cfg_pub_key' => '0',
    'fieldtable' => 3,
  ),
  4 => 
  array (
    'component' => 'grid',
    'livname' => '嘉宾',
    'proname' => 'guest',
    'cfg_add_key' => '1',
    'cfg_edit_key' => '1',
    'cfg_del_key' => '1',
    'cfg_page_key' => '1',
    'cfg_handsort_key' => '1',
    'cfg_brower_key' => '0',
    'cfg_top_key' => '0',
    'cfg_pub_key' => '0',
    'fieldtable' => 4,
  ),
  5 => 
  array (
    'component' => 'grid',
    'livname' => '会议安排',
    'proname' => 'meeting',
    'cfg_add_key' => '1',
    'cfg_edit_key' => '1',
    'cfg_del_key' => '1',
    'cfg_page_key' => '1',
    'cfg_handsort_key' => '1',
    'cfg_brower_key' => '0',
    'cfg_top_key' => '0',
    'cfg_pub_key' => '0',
    'fieldtable' => 5,
  ),
);
?>